
package in.crossword.bookprice.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import in.crossword.bookprice.types.BookName;
import in.crossword.bookprice.types.ObjectFactory;
import in.crossword.bookprice.types.Price;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BookPrice", targetNamespace = "http://www.crossword.in/BookPrice/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookPrice {


    /**
     * 
     * @param bookName
     * @return
     *     returns in.crossword.bookprice.types.Price
     */
    @WebMethod(action = "http://www.crossword.in/BookPrice/grtPrice")
    @WebResult(name = "Price", targetNamespace = "http://www.crossword.in/BookPrice/types", partName = "Price")
    public Price grtPrice(
        @WebParam(name = "BookName", targetNamespace = "http://www.crossword.in/BookPrice/types", partName = "BookName")
        BookName bookName);

}
