
package in.crossword.bookprice.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BookPriceService", targetNamespace = "http://www.crossword.in/BookPrice/wsdl", wsdlLocation = "file:/C:/Users/gandhpra/Documents/workspace/Web1/WebContent/WEB-INF/BookPrice.wsdl")
public class BookPriceService
    extends Service
{

    private final static URL BOOKPRICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(in.crossword.bookprice.wsdl.BookPriceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = in.crossword.bookprice.wsdl.BookPriceService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/gandhpra/Documents/workspace/Web1/WebContent/WEB-INF/BookPrice.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/gandhpra/Documents/workspace/Web1/WebContent/WEB-INF/BookPrice.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BOOKPRICESERVICE_WSDL_LOCATION = url;
    }

    public BookPriceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookPriceService() {
        super(BOOKPRICESERVICE_WSDL_LOCATION, new QName("http://www.crossword.in/BookPrice/wsdl", "BookPriceService"));
    }

    /**
     * 
     * @return
     *     returns BookPrice
     */
    @WebEndpoint(name = "BookPricePort")
    public BookPrice getBookPricePort() {
        return super.getPort(new QName("http://www.crossword.in/BookPrice/wsdl", "BookPricePort"), BookPrice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookPrice
     */
    @WebEndpoint(name = "BookPricePort")
    public BookPrice getBookPricePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.crossword.in/BookPrice/wsdl", "BookPricePort"), BookPrice.class, features);
    }

}
